### ISSUE TITLE
ld: library not found for -lFlurry-iOS-SDK

### ISSUE THREAD

**Issue by Fantasim** [xxsnakerxx/react-native-flurry-analytics#8]
Hi,

When i try to build my app with react-native-flurry-analytics, i handle this error :

http://www.yagoshack.fr/?v=capturrhr.png

i dont understan't because header search path is linked : 

http://www.yagoshack.fr/?v=capturoco.png

**Comment by zendern** [comment]
@Fantasim I believe this is not an issue. 

Try closing the Xcode project and instead open `<project name>.xcworkspace`. Since this is using Cocopods you need to use the workspace instead for everything to get resolved correctly.

I had the same problem as you and stumbled on this article and after seeing the line about xcworkspace it made sense.

https://shift.infinite.red/beginner-s-guide-to-using-cocoapods-with-react-native-46cb4d372995

**Comment by Fantasim** [comment]
Thanks i'll see that :)
